### ISSUE TITLE
Personaje saltarín

### ISSUE THREAD

**Issue by oihanion** [SymplecticGames/Runok#19]
Cuando bajaba el personaje en una plataforma en el primer nivel parecía que estaba saltando o por lo menos reproducía esa animación.

Prioridad: baja

Para reproducir el error: subir al personaje en una plataforma móvil y esperar a que esta baje.

**Comment by Dariasteam** [comment]
Dumplicado de https://github.com/SymplecticGames/Runok/issues/2
