### ISSUE TITLE
Interludios (pantalla con el lore de Runok)

### ISSUE THREAD

**Issue by GonzaloGNogales** [SymplecticGames/Runok#32]

**Comment by Dariasteam** [comment]
Sï, esto era algo que quería comentar que hay que añadir para no desaprovechar la historia. Creo que con esto podemos matar dos pájaros de un tiro si en lugar de hacerlos obligatorios y medio desesperantes como les pasó a los de fishinglegends lo ponemos en objetos coleccionables como los que sugirió Julio. 

Mi idea es algo tipo los pergaminos que explican los controles pero con dos dibujitos y un minitexto. Tiramos por el mapa objetos que al cogerlos te muestren el siguiente pergamino. SI has conseguido coger todos los objetos pues te enteras de la historia completa, por lo que ese es el incentivo para buscarlos. Hacemos que coger cualquier objeto de cualquier mapa siempre muestre el siguietne pergamino para que alguien pueda conocer la historia pero sin lelgar al final si se pierde objetos, pero no le ocurra que consigue solo el capítulo 1 y 9 y no entienda nada.

Si les parece lo discutimos por aquí @DiegoK98 @shykibi @GonzaloGNogales

**Comment by GonzaloGNogales** [comment]
La cosa es que @shykibi ya se ha currado una introducción muy cortita y muy chula con dibujitos por lo que esto está prácticamente ya terminado a falta de un par de detalles que está completando, por lo que yo creo que mejor lo dejamos así, y ya en la siguiente reunión que estemos todos lo vemos terminado, pero ya lo hemos revisado @DiegoK98 y yo y nos ha parecido muy chulo.
